services:
  - name: web
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn==20.1.0
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
