# Generated by Django 5.0.1 on 2024-01-23 13:31

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquestion',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.file_url),
        ),
    ]
