# Generated by Django 5.0.1 on 2024-01-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0002_alter_setsession_subject_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsession',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
